### PR TITLE
chore: Configure and integrate pre-commit

### PR DESCRIPTION
**Pull request by apexDev37**
## Description
This branch introduces `chore` patches to the **recall-server**. This PR's primary goal is to integrate and configure `pre-commit` to locally improve developer feedback and run essential quality checks for each contribution made. This advances the contributor team's remarks to improve [maintainability](#17 ) and quality while considering developer experience.

resolves: #31 

- Pre-commit implicitly creates a dependency on the user's local development environment, placing the onus of responsibility and trust on the user. Consequently, users can easily bypass the minimal setup required to enforce hook checks on commits.
- All `pre-commit` hook violations were resolved to ensure the repo is pushed in a stable/valid state.
- Version management of the hooks and configurations of hook behavior is the upfront cost incurred.

## Testing
Tests run: `N/A`
> This patch is of type **chore** and does not add/update any src modules.

## Additional
**General**
- [DevEX] Add make target `prepush` as a simple interface to `pre-commit` validation checks.
- [Docs] Update `CONTRIBUTING.md` docs to inform users to verify local changes.
- [Issues] This PR completes the final task and resolves the following [issue](#31).
- [Issues] A subsequent issue and PR will be opened to integrate [`pre-commit-ci`](https://pre-commit.ci/) to address the following:
  - Automatic dependency management of hook versions
  - Integrating remote CI checks on GitHub to work around users skipping pre-commit setup (**not recommended**) locally.
- [Recommendation] An `autosquash` merge commit for this PR may not be ideal for the commit history. The multiple modifications in [`chore(pre-commit): Run and resolve local checks`](https://github.com/Friendsofthepeople/django-recall-server/commit/d512006a15cedd9e8a8b24153121db67eda5cda6) may obscure the semantics of the other contributions made.

**Merge checklist:**
Check off if complete *or* not applicable:
- [x] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings)
- [x] Fixup commits are squashed away
- [x] Unit tests added/updated
- [x] Manual testing instructions provided
- [x] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Review by C-o-m-o-n — APPROVED** [review]
Hey. I reviewed your updates and they look good to me. However, The docs seems to be broken. I'm not sure if it works on the main branch, but it's working on mine. I will however proceed to merging since this is not such a big deal yet, but I'll appreciate it if you would check it out

KEEP ON THE AMAZING WORK YOU ARE DOING :)

image

**Comment by C-o-m-o-n** [comment]
> Hey. I reviewed your updates and they look good to me. However, The docs seems to be broken. I'm not sure if it works on the main branch, but it's working on mine. I will however proceed to merging since this is not such a big deal yet, but I'll appreciate it if you would check it out
> 
> KEEP ON THE AMAZING WORK YOU ARE DOING :)
> 
> image

I f you manage to fix it, just push to the same branch. No need of creating a new branch for it.

**Comment by apexDev37** [comment]
Hey @C-o-m-o-n,
Interesting... I don't think any changes touched the `swagger` impl.
I can check it out today and try to resolve the issue...

**Comment by C-o-m-o-n** [comment]
> Hey @C-o-m-o-n, Interesting... I don't think any changes touched the `swagger` impl. I can check it out today and try to resolve the issue...

There are two impl of the docs: one for swagger, and the other for redoc, kindly check it out  as well.

**Comment by apexDev37** [comment]
> There are two impl of the docs: one for swagger, and the other for redoc, kindly check it out as well.

Noted.

I need a bit more info.
- You mentioned it working on your machine but not on `main`, please clarify.

I also noticed `app.github.dev` in the docs URL.
- Are you working in GitHub Codespaces (or a similar cloud-hosted dev environment) or is this failing in a `staging` deployment/environment?

**Comment by C-o-m-o-n** [comment]
> > There are two impl of the docs: one for swagger, and the other for redoc, kindly check it out as well.
> 
> Noted.
> 
> I need a bit more info.
> 
> * You mentioned it working on your machine but not on `main`, please clarify.
> 
> I also noticed `app.github.dev` in the docs URL.
> 
> * Are you working in GitHub Codespaces (or a similar cloud-hosted dev environment) or is this failing in a `staging` deployment/environment?


- The last time I used the main branch it was working. I've been working on deploying so I created a new branch. I've not been on the main branch for a while. I'm on the dev branch. I guess it's not working now since I've merged a couple of commits to main. I have been reviewing on new codespaces everytime before marging, that's may be the reason why I may have missed it. I have just been cherypicking commits to the dev branch

- yes I'm working on codespaces. I my machine is slow to handle all these docker staff.

**Comment by apexDev37** [comment]
The error appears to stem from a `model` refactor to migrate from inheriting from `models.Model` to `mixins.OwnerlessAbstract`. This custom base class defines a primary key, `tokenized_id` for each sub-classing model, but the model's serializer still requires a field `id`. These types of errors are common in non-statically typed languages and end up being detected at runtime. 

```
# Logs on access to swagger docs endpoint
...
web-1  |     raise ImproperlyConfigured(
web-1  | django.core.exceptions.ImproperlyConfigured: Field name `id` is not valid for model `MemberOfParliament` in `recall_server.mps.serializers.MemberOfParliamentSerializer`
```

**Comment by apexDev37** [comment]
This fix partially resolves the problem. The update must also be applied to any serializers with an updated parent model.
Given the significance of the patch, I'll isolate these changes in a `fix` branch.

swagger

This could also mean that a _smoke_ test can be designed around the swagger docs to implicitly check the health _status_ of the API at a high level🧪

**Pull request merged**
